### ISSUE TITLE
gl-style-spritify too many open files

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-style-spec#346]
I got "too many open files" error when trying gl-style-spritify on a directory with 1504 files (752 normal + 752 retina). Switching to graceful-fs fixed the problem.

Not sending this as a pull request as it is probably the wrong way to fix this problem. I really do not know..

```
diff --git a/bin/gl-style-spritify b/bin/gl-style-spritify
index 053976c..25f4617 100755
--- a/bin/gl-style-spritify
+++ b/bin/gl-style-spritify
@@ -1,6 +1,10 @@
 #!/usr/bin/env node
 "use strict";
 
+var realFs = require('fs')
+var gracefulFs = require('graceful-fs')
+gracefulFs.gracefulify(realFs)
+
 var fs = require('fs');
 var path = require('path');
 
diff --git a/package.json b/package.json
index dc65bf4..b0c9eae 100644
--- a/package.json
+++ b/package.json
@@ -18,7 +18,8 @@
     "minimist": "0.0.8",
     "rw": "^0.1.4",
     "sort-object": "^0.3.2",
-    "spritesmith": "1.3.0"
+    "spritesmith": "1.3.0",
+    "graceful-fs": "4.1.2"
   },
   "devDependencies": {
     "coveralls": "~2.10.0",
```

BTW, here is the error I got.
```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files 's52icons.png'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at /Users/halset/projects/ext/mapbox-gl-style-spec/bin/gl-style-spritify:69:12
    at /Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/async/lib/async.js:485:30
    at /Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/async/lib/async.js:485:30
    at /Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/pixelsmith/node_modules/async/lib/async.js:541:30
    at /Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/pixelsmith/node_modules/async/lib/async.js:251:17
    at done (/Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/pixelsmith/node_modules/async/lib/async.js:126:15)
    at /Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/pixelsmith/node_modules/async/lib/async.js:32:16
    at /Users/halset/projects/ext/mapbox-gl-style-spec/node_modules/spritesmith/node_modules/pixelsmith/node_modules/async/lib/async.js:248:21
```

**Comment by jfirebaugh** [comment]
See also #300.
